### ISSUE TITLE
Meeting agenda for 2018-03-20

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-docs/team#10]
time: 19:00 UTC http://everytimezone.com/#2018-3-20,420,cn3

location: Mozilla IRC, `#rust-docs`

Nominated issues/PRs: https://github.com/rust-lang/rust/issues?q=is%3Aopen+label%3AT-doc+label%3AI-nominated

Please leave comments with agenda topics!

**Comment by QuietMisdreavus** [comment]
Should we plan for an IRC meeting at the usual timeslot next week? The whole "main" team will be in Berlin for the Rust All-Hands, so we'll be meeting during the week anyway.

**Comment by steveklabnik** [comment]
Given we have no real agenda this week, I am likely to just skip it, specifically because many of us will be together next week. I guess it depends if we have a real agenda or not.

I feel bad about our lack of agenda... maybe a good topic for next week, heh.

**Comment by frewsxcv** [comment]
it looks like the community team has a couple documents indicating what it means to be part of the team. wonder if we should have something similar for the docs team...

* https://github.com/rust-community/team/blob/master/rfcs/team-membership.md
* https://github.com/rust-community/team/blob/master/rfcs/observer-policy.md

**Comment by steveklabnik** [comment]
We agreed that @frewsxcv 's suggestion is a good idea, but it's not clear who has the time to do it right now. @frewsxcv want to open up an issue tracking it?

Next meeting agenda: https://github.com/rust-docs/team/issues/14

**Comment by QuietMisdreavus** [comment]
Logs for today's meeting: <https://botbot.me/mozilla/rust-docs/msg/98568583/>
