### ISSUE TITLE
Crazy idea: search across the entire bookshelf

### ISSUE THREAD

**Issue by mattico** [rust-docs/team#13]
There are a lot of books on the bookshelf, and sometimes it's not obvious which one can answer your question. Googling with `site:doc.rust-lang.org` [works okay](https://www.google.com/search?q=specialization+site%3Adoc.rust-lang.org), but Google doesn't understand versions and formatting so there's opportunity to improve. A few days ago I realized it would be "easy" to make a global search index for a bunch of MDBooks by parsing their document stores and inserting it into another index. This is the result (starting in TRPL and ending in the Nomicon):

![search-demo](https://user-images.githubusercontent.com/853158/38204675-7c194316-3669-11e8-8ad8-701cf9c7377a.gif)

Code here: https://github.com/mattico/global-search
The basic process:

- Add global search button and JS to MDBook theme
- Build books
- Parse document store from each book's search index
- Insert documents from document store into Tantivy search index
- Start Actix server to respond to search queries with JSON

I think this approach just needs a bit of polish to be workable. Another possibility is to use Amazon CloudSearch and have the tool run on Travis to submit changes to the index.

I'm interested in pushing this forward in my spare time, but I thought I'd ask: what do you think? Is this desirable? Is this a good approach? How could we deploy this? etc.

**Comment by marioidival** [comment]
Lovely

**Comment by steveklabnik** [comment]
This is very cool!

It'd be neat if it could say which book it was from...

**Comment by fulmicoton** [comment]
@mattico Awesome! Let me know if you need help with `tantivy`.
