### ISSUE TITLE
Agenda for 2018-03-13

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-docs/team#9]
time: 19:00 UTC http://everytimezone.com/#2018-3-13,420,cn3

location: Mozilla IRC, `#rust-docs`

Nominated Issues/PRs: https://github.com/rust-lang/rust/issues?q=is%3Aopen+label%3AT-doc+label%3AI-nominated

Please leave comments with agenda topics!

**Comment by frewsxcv** [comment]
Might be worth discussions plans and strategies for Rust All-Hands in a couple weeks. What projects and initiatives would be best to work on while we're all together in person?

**Comment by QuietMisdreavus** [comment]
Logs at <https://botbot.me/mozilla/rust-docs/msg/97767348/>

- Attendance: frewsxcv, misdreavus, Havvy, alercah
- No nominated issues
- frewsxcv mentioned the Rust All-Hands as a chance to collaborate or pair on projects
  - misdreavus brought up https://github.com/rust-docs/team/issues/8 again

Next meeting on 2018-03-20 19:00 UTC, agenda: https://github.com/rust-docs/team/issues/10
